FROM python:3.9

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt --verbose


COPY . .


EXPOSE 8501

CMD ["streamlit", "run", "app.py"]